### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Yekul10** [Prunoideae/CustomDisc#1]
Minecraft crashed when I loaded the mod.
https://pastebin.com/nkFVTHLi

**Comment by Prunoideae** [comment]
err, i can't find much on this error report, could you please post the latest.log to help me get some information more detailed?

**Comment by Prunoideae** [comment]
Oh, i see where the issue is, you may entered duplicated entries, which caused the mod to load a item with its name in registry twice. I will add a duplication check in the next version, you may check your own cfg file to fix the problem.

**Comment by Yekul10** [comment]
The game starts now, but the disc textures and sounds don't work. Maybe you could look at what's wrong in the files?
https://pastebin.com/N9vKr0sw

**Comment by Prunoideae** [comment]
you need to stick to the example.
the string you listed in the cfg, is what called "registry name" of the disc, and all the resources loading depends on it
for example, you have a test1 in the config, then a customdisc:test1 will be added into the game, and the game will find for test1.json,test1.png and test1.ogg in folder related. you may modify the sounds.json to make it loads ogg files with different names, but the sound event name is explicit to test1 and cannot be changed
you entered the titles of disks in the config, that caused the game failed to find textures and audios for it so thats the problem.
