### ISSUE TITLE
Crash Report 1.12.2 version 1.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Prunoideae/CustomDisc#2]
[crash-2019-06-23_12.26.35-client.txt](https://github.com/Prunoideae/CustomDisc/files/3318348/crash-2019-06-23_12.26.35-client.txt)

**Comment by Prunoideae** [comment]
Seems like newer version of forge changed some field in resource managing which makes reflection can't find correct ones to override then caused the game failed, maybe a fix will come out after all my term exams finished...
You can roll back forge to version 2768 or a little newer to avoid this crash.

**Comment by Prunoideae** [comment]
Weird, recompiling code in 2838 will not throw this error but can't be used in 2768, I will launch a version for forge after 2838 tomorrow.

**Comment by P3rf3ctXZer0** [comment]
Actually I cannot rollback thanks to Quark and JEI

**Comment by simplebunsen** [comment]
Same exact problem here: https://paste.dimdev.org/awekikivap.rb
Using 2838 as well.

**Comment by P3rf3ctXZer0** [comment]
Just remove custom disc - dev doesn't want to fix it. They would rather you just revert @simplebunsen

**Comment by Prunoideae** [comment]
1. The custom disc used some very tricky code - to tell minecraft code how the resource is loaded, to make a independent resource folder for you to add songs into, the field may change as the forge changed the version, then there would be an error, I COULD to write a version that doesn't use reflection to change the loader, but this will require mods like ResourceLoader or something to work, which is not fun and needs a lot of code.
2. That's even not a problem, if I have enough time, but unfortunately, I don't have, as now I'm working on two papers about the stupid invertebrate Planaria, I MUST finish it by the Sept. or my professor will be really pissed off and I will lost everything I have now.

So there won't be a clear fix in the recent time, and I can't really help.
@simplebunsen @P3rf3ctXZer0

**Comment by shackhorn** [comment]
Hello from the future. Any plans to fix this? Figured it was worth an ask haha
